POST https://panda-market-api.vercel.app/auth/signUp
Content-Type: application/json

{
  "nickname": "코드잇Test",
  "email": "codeitTest@example.com",
  "password": "p@ssword",
  "passwordConfirmation": "p@ssword"
}

###

POST https://panda-market-api.vercel.app/auth/signIn
Content-Type: application/json

{
  "email": "codeitTest@example.com",
  "password": "p@ssword"
}